# contents of a minimal pyproject.toml 

[build-system] 
requires = ["hatchling"] 
build-backend = "hatchling.build" 

[project] 
name = "example_package_sergey" 
dynamic = ["version"] 
dependencies = ["numpy"]
readme="README.md"

[tool.hatch]
version.path = "src/example_package_sergey/__init__.py"


[project.optional-dependencies]
test = ["pytest"]

